version: 2
updates:
  - package-ecosystem: "nuget"
    directories: 
      - "/CityVilleDotnet.Api"
      - "/CityVilleDotnet.Common"
      - "/CityVilleDotnet.Domain"
      - "/CityVilleDotnet.Persistence"
      - "/FluorineFX"
      - "/test/CityVilleDotnet.Factory"
      - "/test/CityVilleDotnet.Test.Domain"
      - "/test/CityVilleDotnet.Test.Integration"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
