version: 2
updates:
  - package-ecosystem: "nuget"
    directories: 
      - "/CityVilleDotnet.Api"
      - "/CityVilleDotnet.Common"
      - "/CityVilleDotnet.Domain"
      - "/CityVilleDotnet.Persistence"
      - "/FluorineFX"
    schedule:
      interval: "weekly"
