services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cityville-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - cityville-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 25
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cityville-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
      - ConnectionStrings__Database=Server=sqlserver,1433;Database=CityVille;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__Using__1=Serilog.Sinks.File
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Warning
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__0__Args__restrictedToMinimumLevel=Information
      - Serilog__WriteTo__1__Name=File
      - Serilog__WriteTo__1__Args__path=/app/logs/applog-.txt
      - Serilog__WriteTo__1__Args__rollingInterval=Day
      - Serilog__WriteTo__1__Args__rollOnFileSizeLimit=true
      - Serilog__WriteTo__1__Args__restrictedToMinimumLevel=Information
      - Serilog__WriteTo__1__Args__formatter=Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1=WithMachineName
      - Serilog__Properties__ApplicationName=CityVilleDotnet
    ports:
      - "8080:8080"
    volumes:
      - ./wwwroot:/app/wwwroot
      - ./logs:/app/logs
    networks:
      - cityville-network
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  cityville-network:
    driver: bridge