namespace CityVilleDotnet.Domain.Enums;

public enum BuildingClassType
{
    Business = 0,
    Residence = 1,
    Decoration = 2,
    Plot = 3,
    Wilderness = 4,
    Municipal = 5,
    Storage = 6,
    ConstructionSite = 7,
    LotSite = 8,
    Road = 9,
    TrainTracks = 10,
    TrainStation = 11,
    Ship = 12,
    Sidewalk = 13,
    Landmark = 14,
    Factory = 15,
    Headquarter = 16,
    Pier = 17,
    SocialBusiness = 18,
    Bridge = 19,
    PowerStation = 20,
    Hotel = 21,
    CraftingCenter = 22,
    DockHouse = 23,
    HarvestableShip = 24,
    Skyscraper = 25,
    Wonder = 26,
    Garden = 27,
    Mall = 28,
    University = 29,
    MunicipalCenter = 30,
    FerryShip = 31,
    BusStop = 32,
    BusStation = 33,
    Subway = 34,
    Airplane = 35,
    ZooEnclosure = 36,
    MechanicMapResource = 37,
    BridgePart = 38,
    TimedHarvestableResource = 39,
    ItemStorage = 40,
    BasePier = 41,
    TimedBusiness = 42
}